name: AdditionalWorldeditBrushes

main: de.iani.additionalWorldeditBrushes.AdditionalWorldeditBrushes

version: 0.1.2
api-version: 1.13
depend: [WorldEdit, CubesideUtils]
author: Brokkonaut
description: AdditionalWorldeditBrushes

commands:
  abrush:
    description: Select Brush
  replacebiome:
    description: Replace biomes in a radius